/*
Copyright 2022 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// HorizonSourceListerExpansion allows custom methods to be added to
// HorizonSourceLister.
type HorizonSourceListerExpansion interface{}

// HorizonSourceNamespaceListerExpansion allows custom methods to be added to
// HorizonSourceNamespaceLister.
type HorizonSourceNamespaceListerExpansion interface{}

// VSphereBindingListerExpansion allows custom methods to be added to
// VSphereBindingLister.
type VSphereBindingListerExpansion interface{}

// VSphereBindingNamespaceListerExpansion allows custom methods to be added to
// VSphereBindingNamespaceLister.
type VSphereBindingNamespaceListerExpansion interface{}

// VSphereSourceListerExpansion allows custom methods to be added to
// VSphereSourceLister.
type VSphereSourceListerExpansion interface{}

// VSphereSourceNamespaceListerExpansion allows custom methods to be added to
// VSphereSourceNamespaceLister.
type VSphereSourceNamespaceListerExpansion interface{}
