/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/sources-for-knative/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHorizonSources implements HorizonSourceInterface
type FakeHorizonSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var horizonsourcesResource = schema.GroupVersionResource{Group: "sources.tanzu.vmware.com", Version: "v1alpha1", Resource: "horizonsources"}

var horizonsourcesKind = schema.GroupVersionKind{Group: "sources.tanzu.vmware.com", Version: "v1alpha1", Kind: "HorizonSource"}

// Get takes name of the horizonSource, and returns the corresponding horizonSource object, and an error if there is any.
func (c *FakeHorizonSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HorizonSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(horizonsourcesResource, c.ns, name), &v1alpha1.HorizonSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HorizonSource), err
}

// List takes label and field selectors, and returns the list of HorizonSources that match those selectors.
func (c *FakeHorizonSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HorizonSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(horizonsourcesResource, horizonsourcesKind, c.ns, opts), &v1alpha1.HorizonSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HorizonSourceList{ListMeta: obj.(*v1alpha1.HorizonSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.HorizonSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested horizonSources.
func (c *FakeHorizonSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(horizonsourcesResource, c.ns, opts))

}

// Create takes the representation of a horizonSource and creates it.  Returns the server's representation of the horizonSource, and an error, if there is any.
func (c *FakeHorizonSources) Create(ctx context.Context, horizonSource *v1alpha1.HorizonSource, opts v1.CreateOptions) (result *v1alpha1.HorizonSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(horizonsourcesResource, c.ns, horizonSource), &v1alpha1.HorizonSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HorizonSource), err
}

// Update takes the representation of a horizonSource and updates it. Returns the server's representation of the horizonSource, and an error, if there is any.
func (c *FakeHorizonSources) Update(ctx context.Context, horizonSource *v1alpha1.HorizonSource, opts v1.UpdateOptions) (result *v1alpha1.HorizonSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(horizonsourcesResource, c.ns, horizonSource), &v1alpha1.HorizonSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HorizonSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHorizonSources) UpdateStatus(ctx context.Context, horizonSource *v1alpha1.HorizonSource, opts v1.UpdateOptions) (*v1alpha1.HorizonSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(horizonsourcesResource, "status", c.ns, horizonSource), &v1alpha1.HorizonSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HorizonSource), err
}

// Delete takes name of the horizonSource and deletes it. Returns an error if one occurs.
func (c *FakeHorizonSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(horizonsourcesResource, c.ns, name, opts), &v1alpha1.HorizonSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHorizonSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(horizonsourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HorizonSourceList{})
	return err
}

// Patch applies the patch and returns the patched horizonSource.
func (c *FakeHorizonSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HorizonSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(horizonsourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.HorizonSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HorizonSource), err
}
