apiVersion: sources.tanzu.vmware.com/v1alpha1
kind: VSphereSource
metadata:
 name: vcsim-to-broker
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      name: default

  address: https://vcsim.default.svc.cluster.local
  skipTLSVerify: true
  secretRef:
    name: vsphere-credentials
