/*
Copyright 2022 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type HorizonSourceExpansion interface{}

type VSphereBindingExpansion interface{}

type VSphereSourceExpansion interface{}
