/*
Copyright 2022 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/sources-for-knative/pkg/apis/sources/v1alpha1"
	scheme "github.com/vmware-tanzu/sources-for-knative/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VSphereBindingsGetter has a method to return a VSphereBindingInterface.
// A group's client should implement this interface.
type VSphereBindingsGetter interface {
	VSphereBindings(namespace string) VSphereBindingInterface
}

// VSphereBindingInterface has methods to work with VSphereBinding resources.
type VSphereBindingInterface interface {
	Create(ctx context.Context, vSphereBinding *v1alpha1.VSphereBinding, opts v1.CreateOptions) (*v1alpha1.VSphereBinding, error)
	Update(ctx context.Context, vSphereBinding *v1alpha1.VSphereBinding, opts v1.UpdateOptions) (*v1alpha1.VSphereBinding, error)
	UpdateStatus(ctx context.Context, vSphereBinding *v1alpha1.VSphereBinding, opts v1.UpdateOptions) (*v1alpha1.VSphereBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VSphereBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VSphereBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VSphereBinding, err error)
	VSphereBindingExpansion
}

// vSphereBindings implements VSphereBindingInterface
type vSphereBindings struct {
	client rest.Interface
	ns     string
}

// newVSphereBindings returns a VSphereBindings
func newVSphereBindings(c *SourcesV1alpha1Client, namespace string) *vSphereBindings {
	return &vSphereBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vSphereBinding, and returns the corresponding vSphereBinding object, and an error if there is any.
func (c *vSphereBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VSphereBinding, err error) {
	result = &v1alpha1.VSphereBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vspherebindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VSphereBindings that match those selectors.
func (c *vSphereBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VSphereBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VSphereBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vspherebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vSphereBindings.
func (c *vSphereBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vspherebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vSphereBinding and creates it.  Returns the server's representation of the vSphereBinding, and an error, if there is any.
func (c *vSphereBindings) Create(ctx context.Context, vSphereBinding *v1alpha1.VSphereBinding, opts v1.CreateOptions) (result *v1alpha1.VSphereBinding, err error) {
	result = &v1alpha1.VSphereBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vspherebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vSphereBinding).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vSphereBinding and updates it. Returns the server's representation of the vSphereBinding, and an error, if there is any.
func (c *vSphereBindings) Update(ctx context.Context, vSphereBinding *v1alpha1.VSphereBinding, opts v1.UpdateOptions) (result *v1alpha1.VSphereBinding, err error) {
	result = &v1alpha1.VSphereBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vspherebindings").
		Name(vSphereBinding.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vSphereBinding).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vSphereBindings) UpdateStatus(ctx context.Context, vSphereBinding *v1alpha1.VSphereBinding, opts v1.UpdateOptions) (result *v1alpha1.VSphereBinding, err error) {
	result = &v1alpha1.VSphereBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vspherebindings").
		Name(vSphereBinding.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vSphereBinding).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vSphereBinding and deletes it. Returns an error if one occurs.
func (c *vSphereBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vspherebindings").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vSphereBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vspherebindings").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vSphereBinding.
func (c *vSphereBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VSphereBinding, err error) {
	result = &v1alpha1.VSphereBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vspherebindings").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
