/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/sources-for-knative/pkg/apis/sources/v1alpha1"
	scheme "github.com/vmware-tanzu/sources-for-knative/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VSphereSourcesGetter has a method to return a VSphereSourceInterface.
// A group's client should implement this interface.
type VSphereSourcesGetter interface {
	VSphereSources(namespace string) VSphereSourceInterface
}

// VSphereSourceInterface has methods to work with VSphereSource resources.
type VSphereSourceInterface interface {
	Create(ctx context.Context, vSphereSource *v1alpha1.VSphereSource, opts v1.CreateOptions) (*v1alpha1.VSphereSource, error)
	Update(ctx context.Context, vSphereSource *v1alpha1.VSphereSource, opts v1.UpdateOptions) (*v1alpha1.VSphereSource, error)
	UpdateStatus(ctx context.Context, vSphereSource *v1alpha1.VSphereSource, opts v1.UpdateOptions) (*v1alpha1.VSphereSource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VSphereSource, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VSphereSourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VSphereSource, err error)
	VSphereSourceExpansion
}

// vSphereSources implements VSphereSourceInterface
type vSphereSources struct {
	client rest.Interface
	ns     string
}

// newVSphereSources returns a VSphereSources
func newVSphereSources(c *SourcesV1alpha1Client, namespace string) *vSphereSources {
	return &vSphereSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vSphereSource, and returns the corresponding vSphereSource object, and an error if there is any.
func (c *vSphereSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VSphereSource, err error) {
	result = &v1alpha1.VSphereSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vspheresources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VSphereSources that match those selectors.
func (c *vSphereSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VSphereSourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VSphereSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vspheresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vSphereSources.
func (c *vSphereSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vspheresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vSphereSource and creates it.  Returns the server's representation of the vSphereSource, and an error, if there is any.
func (c *vSphereSources) Create(ctx context.Context, vSphereSource *v1alpha1.VSphereSource, opts v1.CreateOptions) (result *v1alpha1.VSphereSource, err error) {
	result = &v1alpha1.VSphereSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vspheresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vSphereSource).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vSphereSource and updates it. Returns the server's representation of the vSphereSource, and an error, if there is any.
func (c *vSphereSources) Update(ctx context.Context, vSphereSource *v1alpha1.VSphereSource, opts v1.UpdateOptions) (result *v1alpha1.VSphereSource, err error) {
	result = &v1alpha1.VSphereSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vspheresources").
		Name(vSphereSource.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vSphereSource).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vSphereSources) UpdateStatus(ctx context.Context, vSphereSource *v1alpha1.VSphereSource, opts v1.UpdateOptions) (result *v1alpha1.VSphereSource, err error) {
	result = &v1alpha1.VSphereSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vspheresources").
		Name(vSphereSource.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vSphereSource).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vSphereSource and deletes it. Returns an error if one occurs.
func (c *vSphereSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vspheresources").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vSphereSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vspheresources").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vSphereSource.
func (c *vSphereSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VSphereSource, err error) {
	result = &v1alpha1.VSphereSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vspheresources").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
