apiVersion: batch/v1
kind: Job
metadata:
  name: vsphere-script
  labels:
    # Make this Job match the binding!
    role: vsphere-job
spec:
  template:
    metadata:
      labels:
        # So it's easier to list the Pods
        role: vsphere-job        
    spec:
      restartPolicy: Never
      containers:
      - name: create-tag
        image: ko://github.com/vmware-tanzu/sources-for-knative/vendor/github.com/vmware/govmomi/govc
        command: ["/bin/bash", "-c"]
        args:
        - |
          govc tags.category.create testing
          govc tags.create -c testing shrug
