apiVersion: sources.tanzu.vmware.com/v1alpha1
kind: VSphereSource
metadata:
 name: vcsim
spec:
 sink:
   ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: sockeye

 address: https://vcsim.default.svc.cluster.local
 skipTLSVerify: true
 secretRef:
   name: vsphere-credentials
