# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Namespace
metadata:
  name: vmware-sources
  labels:
    istio-injection: enabled
    sources.tanzu.vmware.com/release: devel
