# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: horizon-source-controller
  namespace: vmware-sources
  labels:
    sources.tanzu.vmware.com/release: devel

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: horizon-source-webhook
  namespace: vmware-sources
  labels:
    sources.tanzu.vmware.com/release: devel
