# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vspheresources.sources.tanzu.vmware.com
  labels:
    sources.tanzu.vmware.com/release: devel
    knative.dev/crd-install: "true"
spec:
  group: sources.tanzu.vmware.com
  version: v1alpha1
  names:
    kind: VSphereSource
    plural: vspheresources
    singular: vspheresource
    categories:
    - all
    - knative
    - vsphere
    shortNames:
    - vss
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Address
    type: string
    JSONPath: .status.address.url
  - name: Ready
    type: string
    JSONPath: ".status.conditions[?(@.type=='Ready')].status"
  - name: Reason
    type: string
    JSONPath: ".status.conditions[?(@.type=='Ready')].reason"
