# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  labels:
    role: vsphere-source-webhook
    sources.tanzu.vmware.com/release: devel
  name: vsphere-source-webhook
  namespace: vmware-sources
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    role: vsphere-source-webhook
