# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: vmware-sources
  labels:
    sources.tanzu.vmware.com/release: devel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
        sources.tanzu.vmware.com/release: devel
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        # This is the Go import path for the binary that is containerized
        # and substituted here.
        image: ko://github.com/vmware-tanzu/sources-for-knative/cmd/controller
        resources:
          # Request 2x what we saw running e2e
          requests:
            cpu: 100m
            memory: 100Mi
          # Limit to 10x the request (20x the observed peak during e2e)
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - name: metrics
          containerPort: 9090
        env:
        - name: VSPHERE_ADAPTER
          value: ko://github.com/vmware-tanzu/sources-for-knative/cmd/adapter
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: tanzu.vmware.com/sources
