/*
Copyright 2020 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/vmware-tanzu/sources-for-knative/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// HorizonSources returns a HorizonSourceInformer.
	HorizonSources() HorizonSourceInformer
	// VSphereBindings returns a VSphereBindingInformer.
	VSphereBindings() VSphereBindingInformer
	// VSphereSources returns a VSphereSourceInformer.
	VSphereSources() VSphereSourceInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// HorizonSources returns a HorizonSourceInformer.
func (v *version) HorizonSources() HorizonSourceInformer {
	return &horizonSourceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VSphereBindings returns a VSphereBindingInformer.
func (v *version) VSphereBindings() VSphereBindingInformer {
	return &vSphereBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VSphereSources returns a VSphereSourceInformer.
func (v *version) VSphereSources() VSphereSourceInformer {
	return &vSphereSourceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
