# Copyright 2020 The Knative Authors.
# SPDX-License-Identifier: Apache-2.0

# This file is automagically synced here from github.com/knative-sandbox/knobots
name: 'Close stale'

on:
  schedule:
  - cron: '0 1 * * *'

jobs:

  stale:
    uses: embano1/actions/.github/workflows/stale.yaml@main
